### ISSUE TITLE
Product drop down

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/reclama#5]
Display a dropdown up right for bugs filtering. Populated by Products returned from bug list on event selection.

**Comment by comzeradd** [comment]
@ppapadeas UI mock up

![sho1](https://cloud.githubusercontent.com/assets/939357/6597199/829428d2-c803-11e4-81ab-919f6880d6f2.jpg)

![sho2](https://cloud.githubusercontent.com/assets/939357/6597206/88ebf638-c803-11e4-8e6b-52e13b644db7.jpg)
